### ISSUE TITLE
Not working properly with the lates update

### ISSUE THREAD

**Issue by sidsharths1245** [HliasOuzounis/zen-browser-better-active-tab-indicator#4]
Not sure what happened but after updating to 1.0.1-a.1 it got messed up

![ztiv1ZvjKr](https://github.com/user-attachments/assets/7352e876-78e6-46e6-9f82-50d099660bbe)

**Comment by HliasOuzounis** [comment]
You can add this `.tab-background {
  position: relative;
}` to your userChrome.css while we wait for the theme to be updated on the theme store

**Comment by HliasOuzounis** [comment]
Theme was updated. Should work fine now.
