### ISSUE TITLE
Shows a scroll bar when the last tab is active

### ISSUE THREAD

**Issue by shetty-tejas** [HliasOuzounis/zen-browser-better-active-tab-indicator#5]
![Screenshot 2024-09-23 142143](https://github.com/user-attachments/assets/a2f86b2d-8171-48bb-a4d4-8d127397218c)

**Comment by shetty-tejas** [comment]
Btw, [this](https://github.com/HliasOuzounis/zen-browser-better-active-tab-indicator/issues/4#issuecomment-2358575332) fixes it. Any idea when this version would be released?

**Comment by HliasOuzounis** [comment]
I don't know for sure. I created a [pull request](https://github.com/zen-browser/theme-store/pull/440) to the theme store and I'm waiting for it to be accepted. (I tried before and it got [closed](https://github.com/zen-browser/theme-store/pull/395)). It shouldn't take more than 3-4 days.
